# Generated by Django 4.1 on 2024-05-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnoeud',
            name='nd_coderat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tnoeud'),
        ),
    ]
