# Generated by Django 4.1 on 2024-05-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_tnoeud_nd_coderat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnoeud',
            name='nd_type_ep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ltechnologietype'),
        ),
    ]
