# Generated by Django 4.1 on 2024-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_tnoeud_nd_type_ep'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSuf',
            fields=[
                ('sf_code', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('sf_escal', models.CharField(blank=True, max_length=20)),
                ('sf_etage', models.CharField(blank=True, max_length=20)),
                ('sf_type', models.CharField(max_length=1)),
                ('sf_prop', models.CharField(blank=True, max_length=254)),
                ('sf_resid', models.CharField(blank=True, max_length=254)),
                ('sf_local', models.CharField(blank=True, max_length=254)),
                ('sf_racco', models.CharField(blank=True, max_length=2)),
                ('sf_comment', models.CharField(blank=True, max_length=254)),
                ('sf_creadat', models.DateTimeField(blank=True, null=True)),
                ('sf_majdate', models.DateTimeField(blank=True, null=True)),
                ('sf_majsrc', models.CharField(blank=True, max_length=254)),
                ('sf_abddate', models.DateField(blank=True, null=True)),
                ('sf_abdsrc', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
