# Generated by Django 4.1 on 2024-05-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_tsuf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsuf',
            name='tnoeud_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.tnoeud'),
            preserve_default=False,
        ),
    ]
